---
- name: "Fail if no agents are defined"
  fail: msg="No agents defined in host_vars or group_vars for host"
  when_unset: ${galicaster_agents}
  tags:
    - galidasher
    - checks

- name: "Fail when Matterhorn settings are absent"
  fail: msg="Matterhorn settings are not defined in host_vars or group_vars for host"
  when_unset: ${matterhorn}
  tags:
    - galidasher
    - checks

- name: "Fail when local directory with VNC passfiles is not defined"
  fail: msg="Local directory with VNC passfiles is not defined in host_vars or group_vars for host"
  when_unset: ${vnc_local_dir_pass}
  tags:
    - galidasher
    - checks