---
# Create Galidasher destination directory
- name: Create Galidasher destination directory: {{galidasher.dest}}
  file: path={{galidasher.dest}} state=directory
  tags:
    - galidasher

# Fetch MH dashboard from Git
- name: Fetch MH dashboard: {{galidasher.git}}
  git: repo={{galidasher.git}} dest={{galidasher.dest}}
  tags:
    - galidasher

# Create Galidasher VNC directory
- name: Create Galidasher VNC directory: {{galidasher.vnc.dest_dir}}
  file: path={{galidasher.vnc.dest_dir}} state=directory
  tags:
    - galidasher

# Link MH dashboard web folder to webroot
- name: Link {{galidasher.dest}}/web to {{galidasher.webroot}}
  file: src={{galidasher.dest}}/web dest={{galidasher.webroot}} state=link
  tags:
    - galidasher

# Install Galidasher config file
- name: Install Galidasher config file: {{galidasher.conf}}
  template: src=templates/dashboard.conf.j2 dest={{galidasher.conf}} owner=root group=root mode=0755
  tags:
    - galidasher

# Cronjob update agents.json from MH server
- name: Cronjob agents.json updater: {{galidasher.script}}
  cron: name="Update MH dashboard agents every 5 minutes" minute="*/5" job="{{galidasher.script}} -c {{galidasher.conf}} >> {{galidasher.logfile}}"
  tags:
    - galidasher

# Install Galidasher logrotate file
- name: Install Galidasher logrotate file: {{galidasher.logrotate}}
  template: src=templates/galidasher.logrotate.j2 dest={{galidasher.logrotate}} owner=root group=root mode=0644
  tags:
    - galidasher


# Transfer VNC password file
- name: Transfer VNC passfiles: {{galidasher.vnc.local_dir}}
  copy: src={{item}} dest={{galidasher.vnc.dest_dir}} owner=root group=root mode=0644
  with_fileglob:
    - {{galidasher.vnc.local_dir}}/*
  tags:
    - galidasher

# Create agents.ini file
- name: Create agents.conf file: add vncpasswdFile entry
  ini_file: dest={{galidasher.dest}}/etc/mh-dashboard/agents/agents.conf section={{item.name}} option=vncpasswdFile value={{galidasher.vnc.dest_dir}}/{{item.vnc.passfile}}
  with_items: {{agents}}
  tags:
    - galidasher

# Create agents.ini file
- name: Create agents.conf file: add VNCPort entry
  ini_file: dest={{galidasher.dest}}/etc/mh-dashboard/agents/agents.conf section={{item.name}} option=VNCPort value={{item.vnc.port}}
  with_items: {{agents}}
  tags:
    - galidasher

# Create agents.ini file
- name: Create agents.conf file: add campus entry
  ini_file: dest={{galidasher.dest}}/etc/mh-dashboard/agents/agents.conf section={{item.name}} option=campus value={{item.campus}}
  when: {{item.campus}} is defined
  with_items: {{agents}}
  tags:
    - galidasher

# Create agents.ini file
- name: Create agents.conf file: add campus entry
  ini_file: dest={{galidasher.dest}}/etc/mh-dashboard/agents/agents.conf section={{item.name}} option=campus value={{item.campus}}
  when: {{item.campus}} is defined
  with_items: {{agents}}
  tags:
    - galidasher

# Create agents.ini file
- name: Create agents.conf file: add building entry
  ini_file: dest={{galidasher.dest}}/etc/mh-dashboard/agents/agents.conf section={{item.name}} option=building value={{item.building}}
  when: {{item.building}} is defined
  with_items: {{agents}}
  tags:
    - galidasher

# Create agents.ini file
- name: Create agents.conf file: add center entry
  ini_file: dest={{galidasher.dest}}/etc/mh-dashboard/agents/agents.conf section={{item.name}} option=center value={{item.center}}
  when: {{item.center}} is defined
  with_items: {{agents}}
  tags:
    - galidasher

# Create agents.ini file
- name: Create agents.conf file: add classroom entry
  ini_file: dest={{galidasher.dest}}/etc/mh-dashboard/agents/agents.conf section={{item.name}} option=classroom value={{item.classroom}}
  when: {{item.classroom}} is defined
  with_items: {{agents}}
  tags:
    - galidasher

# Execute agents.json updater
- name: Execute updater: {{galidasher.script}}
  shell: "{{galidasher.script}} -c {{galidasher.conf}} >> {{galidasher.logfile}}"
  tags:
    - galidasher